---
title: 국민-Learn
timezone: UTC
collections:
  docs:
    title: Documentation
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: docs
  values:
    seo:
      type: Article
    _comments:
      category: Group navigation links with this field
      order: Used to sort links in the navigation
- scope:
    path: ''
    type: posts
  values:
    _comments:
      type: Marks the impact of this release
url: https://codertimo.github.io
baseurl:
google_analytics_key: UA-93697929-1
show_full_navigation: true
logo: "/siteicon.png"
description: 누구나 쉽게 코딩을 배울 수 있는 공간
author:
  name: Junseong Kim
  email: codertimo@gmail.com
  twitter:
social:
  name: codertimo-github
  links:
  - https://github.com/codertimo
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
types:
- minor
- major
